# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:oracle
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: springmysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 3000:8080
